[tool.poetry]
name = "target-s3-parquet"
version = "0.0.1"
description = "`target-s3-parquet` is a Singer target for S3Parquet, built with the Meltano SDK for Singer Targets."
authors = ["Gupy"]
keywords = [
    "ELT",
    "S3Parquet",
]
license = "Apache 2.0"

[tool.poetry.dependencies]
python = ">=3.10,<3.13"
requests = "^2.32.3"
singer-sdk = "^0.53.6"
awswrangler = "^3.15.1"
pandas = "^2.2.3"
pyarrow = ">=14.0.2,<23.0.0"

[tool.poetry.group.dev.dependencies]
pytest = "^8.3.5"
tox = "^4.24.2"
flake8 = "^7.1.2"
black = "^24.10.0"
pydocstyle = "^6.3.0"
mypy = "^1.15.0"
types-requests = "^2.32.0.20250328"
isort = "^5.13.2"

[tool.isort]
profile = "black"
multi_line_output = 3 # Vertical Hanging Indent
src_paths = "target_s3_parquet"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
# CLI declaration
target-s3-parquet = 'target_s3_parquet.target:TargetS3Parquet.cli'
